### ISSUE TITLE
Requêtes SQL dans EnchereDAOJDBCImpl

### ISSUE THREAD

**Issue by DamienVassart** [DamienVassart/encheres#10]
Concerne @LydieAlt 
1. SQL_INSERT: Entre 'ENCHERES' et 'VALUES', il manque les noms des colonnes dans lesquelles on inère les données (no_utilisateur, no_article, date_enchere, montant_enchere)
2. SQL_SELECT_ALL: ici, on sélectionne tout sans restriction, donc inutile de préciser no_utilisateur et no_article; attention, l'opérateur `*` ne fonctionnera pas quand tu appelleras la requête dans la méthode `selectAll`, il vaut mieux préciser le nom de toutes les colonnes (no_utilisateur, no_article, ...)
3. SQL_SELECT_BY_ID: les colonnes qu'on veut sélectionner ne sont pas précisées; dans la clause `WHERE`, les deux colonnes noArticles et noUtilisateur devraient être renommées no_article et no_utilisateur et ne pas être séparées par une virgule mais par l'opérateur `AND`
4. SQL_UPDATE: est inutile et doit être supprimée
5. SQL_DELETE: même remarque qu'en **4**
6. Manquent deux requêtes: une `SELECT` par no_article et une `SELECT` par no_utilisateur

**Comment by LydieAlt** [comment]
1-modifié
2-modifié sans * et sans préciser le nom des colonnes du coup?
3-modifié
4-5-lignes supprimées
6- Un peu de mélange dans la préparation des 2 requêtes Select (en cours)

**Comment by DamienVassart** [comment]
1- ok
2- c'est plutôt SELECT (no_utilisateur, no_article, ...) FROM Encheres
3- SELECT (no_utilisateur, no_article, ...) FROM Encheres WHERE...
4/5 - ok
6- ok on verra :)

**Comment by DamienVassart** [comment]
Pour les 2 dernières requêtes (SQL_SelectByNoArticle et SQL_SelectByNoUtilisateur), ce serait plutôt:
- `SELECT (no_utilisateur, no_article, date_enchere, montant_enchere) FROM ENCHERES WHERE no_article = ?;`
- `SELECT (no_utilisateur, no_article, date_enchere, montant_enchere) FROM ENCHERES WHERE no_utilisateur = ?;`

**Comment by LydieAlt** [comment]
ah oui, dans ce sens là c'est mieux, j'ai modifié et fais le push. Merci.
