### ISSUE TITLE
Méthodes dans EnchereDAOJDBCImpl

### ISSUE THREAD

**Issue by DamienVassart** [DamienVassart/encheres#11]
Concerne @LydieAlt 
- `insert` (ligne 37): la signature n'est pas la bonne, mais il y a une autre métode `insert` ligne 137 dont la signature est bonne. Tu peux faire un "couper/coller" du contenu de la première dans la seconde, et ensuite supprimer la première
- `selectAll` (ligne79): dans le bloc `while(rs.next())`, avant le `add` dans `listeEncheres`, il faut appeler tous les setters sur l'objet `enchere`, sinon il reste vide
- Reste à implémenter les autres méthodes

**Comment by LydieAlt** [comment]
1- aille du coup j'ai tout fais descendre avec les modifs précédentes
2-(en cours)
3-

**Comment by DamienVassart** [comment]
Vendredi 10/12 @ 16h:
J'ai pu relever les problèmes qui suivent. Attention, avant toute action, prends bien soin de mettre des commentaires aux numéros de ligne indiqués, car ceux-ci changeront quand tu feras les modifications.

1. Méthode `insert` (ligne **47**): copier tout le contenu de la méthode dans l'autre méthode insert ligne **229** et ensuite supprimer la méthode `insert` de la ligne **47**. A partir de là, il y aura peut-être encore des choses à revoir dans le code de cette méthode
2. Dans la méthode `selectByArticle`, ligne **170**: le setInt attend 2 arguments, un seul est présent
3. Dans la méthode `selectByUtilisateur`, ligne **205**: même remarque qu'en **2**

**Comment by LydieAlt** [comment]
Vendredi 10/12 19h30
- EnchereDAOJDBCImpl : reprise des 3 points+ replacement commentaires + modifs sur 2-3 choses, 
- Imports en trop supprimés sur : EnchereDAO et UtilisateurManager
- Avant push, aucune erreur ni d'attention à apporter
- Pour avis et contrôle
Merci ;)
