### ISSUE TITLE
Etat des lieux 09/12/2021 fin de journée

### ISSUE THREAD

**Issue by DamienVassart** [DamienVassart/encheres#3]
- @dorolib crée ArticleDAOJDBCImpl avec l'aide du groupe
- @LydieAlt apporte les correctifs nécessaires sur UtilisateurManager, EnchereDAO et EnchereDAOJDBCImpl
- En attente du retour du superviseur pour valider la couche back-end

**Comment by LydieAlt** [comment]
@DamienVassart actuellement sur UtilisateurManager, puis en cours sur EnchereDAO et EnchereDAOJDBCImpl, si pas fini, continuité vendredi matin

**Comment by DamienVassart** [comment]
Ok, pas de problème :)
