### ISSUE TITLE
EnchereDAO + EnchereDAOJDBCImpl

### ISSUE THREAD

**Issue by DamienVassart** [DamienVassart/encheres#4]
Concerne @LydieAlt 
- Les méthodes **update** et **delete** sont inutiles: toute enchère est définitive, seule la surenchère est possible, et dans ce cas, on n'opère pas un **update** mais un **insert**
- Les instructions dans l'implémentation de la méthode **selectAll** semblent erronées (à l'intérieur du bloc while(rs.next())): la requête SQL ne demande pas qu'on lui transmette d'identifiant
- Les instructions dans l'implémentation de la méthode **selectById** semblent erronées (à l'intérieur du bloc if(rs.next())): il n'y a pas de méthodesetNoArticle dans la classe Enchere, il faudrait plutôt appeler les méthodes setDateEnchere et setMontantEnchere

En résumé: pour EnchereDAO, vérifier les signatures des méthodes qui figurent dans le fichier organigramme, puis faire un "Add unimplemented methods" dans EnchereDAOJDBCImpl

**Comment by DamienVassart** [comment]
EnchereDAO OK, reste à retravailler EnchereDAOJDBCImpl.
Je ferme cette issue et en rouvre une autre à ce sujet.

**Comment by LydieAlt** [comment]
Vu que j'ai supprimé la méthode delete, car on considère que toute enchère est définitive. 
Est-ce que l'on garde du coup le delete sur EnchereManager? ou peut-être que de ce coté là c'est nécessaire?

**Comment by DamienVassart** [comment]
Bien vu, je regarde

**Comment by DamienVassart** [comment]
J'ai modifié en conséquence, merci :)
