### ISSUE TITLE
Requêtes SQL dans ArticleDAOJDBCImpl révision #2

### ISSUE THREAD

**Issue by DamienVassart** [DamienVassart/encheres#6]
Concerne @dorolib 
1. SQL_INSERT_ARTICLE: le nom de la table **Articles** devrait être changé en **Articles_Vendus**
2. SQL_INSERT_RETRAIT: il faut insérer no_article avant rue, code_postal et ville (ici c'est bien une clé primaire, mais elle n'est pas autogénérée)
3. SQL_UPDATE_ARTICLE: même remarque qu'en **1**
4. SQL_DELETE_ARTICLE: même remarque qu'en **1** et **3**
5. SQL_DELETE_ENCHERE: remplacer no_utilisateur par no_article
6. SQL_SELECT_ALL_ARTICLES: même remarque qu'en **1**, **3** et **4**
7. SQL_SELECT_BY_NAME_ARTICLES: manque FROM Articles_Vendus avant le WHERE
8. SQL_SELECT_BY_ID_ARTICLE: même remarque qu'en **7**

**Comment by dorolib** [comment]
J'ai fait les modifications

**Comment by DamienVassart** [comment]
Vendredi 10/12 @ 16h:
1. SQL_SELECT_BY_ID: il y a une virgule en trop tout au bout de la requête
2. SQL_SelectByNoArticle: la requête n'est pas bonne, ce serait plutôt `SELECT (no_utilisateur, no_article, etc...) FROM Encheres WHERE no_article = ?`
3. SQL_SelectByNoUtilisateur: même remarque qu'en **2**, mais en remplaçant `... WHERE no_article = ?` par `... WHERE no_utilisateur = ?`

**Comment by dorolib** [comment]
C'était des infos plutôt sur le EnchereDAOJDBCImpl de Lydie, je crois?
