### ISSUE TITLE
Classe Enchere

### ISSUE THREAD

**Issue by DamienVassart** [DamienVassart/encheres#9]
Concerne @dorolib 
- Il manque les constructeurs, qui devraient être placés avant les getters / setters
- Le toString est incomplet

**Comment by dorolib** [comment]
Je ne vois pas pour les constructeurs, si/quand tu as le temps, pourrais-tu m'expliquer? Ou dans la réunion de tout à l'heure? 
J'ai ajouté le toString (à vérifier)
